name: Setup
description: this uses for (caching the code, install dependencies) Workflow
inputs:
  working_dir:
    required: true
    description: this is to detect which app should install its dependencies
runs:
  using: "composite"
  steps:
    - name: cache dependencies
      uses: actions/cache@v3
      id: cache
      with:
        key: dep-node-modules-${{ github.sha }}
        path: ~/.npm
    - name: check working_dir
      run: echo "${{ inputs.working_dir }}"
      shell: bash
    - name: install dependencies
      if: ${{ steps.cache.outputs.cache-hit != 'true' }}
      working-directory: ${{ inputs.working_dir }}
      run: npm install
      shell: bash
