apiVersion: v1
clusters:
  - cluster:
      certificate-authority: ./ca.crt
      extensions:
        - extension:
            last-update: Sat, 28 Oct 2023 11:32:17 EET
            provider: minikube.sigs.k8s.io
            version: v1.31.2
          name: cluster_info
      server: https://127.0.0.1:53946
    name: minikube
contexts:
  - context:
      cluster: minikube
      extensions:
        - extension:
            last-update: Sat, 28 Oct 2023 11:32:17 EET
            provider: minikube.sigs.k8s.io
            version: v1.31.2
          name: context_info
      namespace: default
      user: minikube
    name: minikube
current-context: minikube
kind: Config
preferences: {}
users:
  - name: minikube
    user:
      client-certificate: ./client.crt
      client-key: ./client.key
