version: "3.7"
services:
  mongodb:
    container_name: mongodb
    image: mongo
    environment:
      - MONGO_INITDB_DATABASE=users
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=secret
    volumes:
      - "D:/Programming/Courses/Docker, Kubernetes, CICD/challenge:/data/db"
  auth:
    container_name: auth-app
    build: "./auth-api"
    ports:
      - 80:3000
    environment:
      - TOKEN_KEY=secrettoken
  # users:
  #   container_name: users-app
  #   build: "./users-api"
  #   ports:
  #     - 3000:3000
  #   environment:
  #     - MONGO_INITDB_DATABASE=users
  #     - MONGO_INITDB_ROOT_USERNAME=admin
  #     - MONGO_INITDB_ROOT_PASSWORD=secret
  #     - MONGO_DB_HOST=mongodb
  #     - AUTH_API_ADDRESS=""
  #   depends_on:
  #     - mongodb
  #     - auth
volumes:
  data:
