version: "3.7"
services:
  mongodb:
    container_name: mongodb
    image: mongo
    environment:
      - MONGO_INITDB_DATABASE=users
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=secret
    ports:
      - 27017:27017
    volumes:
      - data:/data/db
  auth:
    container_name: auth-app
    # build: "./auth-api"
    image: lodenn/auth-api:latest
    ports:
      - 3000:3000
    environment:
      - TOKEN_KEY=secrettoken
    depends_on:
      - mongodb
  users:
    container_name: users-app
    # build: "./users-api"
    image: lodenn/users-api:latest
    ports:
      - 80:80
    environment:
      - MONGO_INITDB_DATABASE=users
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=secret
      - MONGO_DB_HOST=mongodb
      - AUTH_API_ADDRESS=auth
    depends_on:
      - mongodb
      - auth
volumes:
  data:
