version: "3.7"
services:
  mongodb:
    container_name: mongodb
    image: mongo
    environment:
      - MONGO_INITDB_DATABASE=users
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=secret
    ports:
      - 27017:27017
    volumes:
      - data:/data/db
  auth:
    container_name: auth-app
    image: lodenn/auth-api:latest
    ports:
      - 3000:3000
    environment:
      - TOKEN_KEY=secrettoken
    depends_on:
      - mongodb
  users:
    container_name: users-app
    image: lodenn/users-api:latest
    ports:
      - 80:80
    environment:
      - MONGO_INITDB_DATABASE=users
      - MONGO_INITDB_ROOT_USERNAME=Admin
      - MONGO_INITDB_ROOT_PASSWORD=v4fFNKRLNF9TN5mL
      - MONGO_DB_HOST=cluster0.bzovdv3.mongodb.net
      - AUTH_API_ADDRESS=auth:3000

      # mongodb+srv://Admin:<password>@cluster0.bzovdv3.mongodb.net/?retryWrites=true&w=majority
    depends_on:
      - mongodb
      - auth
volumes:
  data:
