name: Setup Workflow
on:
  workflow_call:
    inputs:
      working_dir:
        description: this input helps to determine which folder should we setup
        required: true
        type: string

jobs:
  setup:
    name: setting up project
    runs-on: ubuntu-latest
    environment: development
    steps:
      - name: Get the code
        uses: actions/checkout@v3
      - name: cache dependencies
        uses: actions/cache@v3
        id: cache
        with:
          key: dep-node-modules-${{ github.sha }}
          path: ~/.npm
      - name: install dependencies
        if: ${{ steps.cache.outputs.cache-hit != 'true' }}
        working-directory: ${{ inputs.working_dir }}
        run: npm install
