name: Auth Workflow
on:
  push:
    branches:
      - auth
env:
  TOKEN_KEY: secrettoken
jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Get the code
        uses: actions/checkout@v3
      - name: Install main dependencies
        uses: ./.github/actions/setup
        with:
          working_dir: users-api
  build-auth-image:
    needs: setup
    uses: ./.github/workflows/image-builder.yml
    with:
      working_dir: auth-api
      image: auth-api
      image-tag: ${{ github.sha }}
    secrets:
      docker_hub_user: ${{ secrets.DOCKER_HUB_USER }}
      docker_hub_pass: ${{ secrets.DOCKER_HUB_PASS }}
  deploy:
    needs: build-auth-image
    runs-on: ubuntu-latest
    environment: development
    permissions:
      contents: write
    steps:
      - name: Get the code
        uses: actions/checkout@v4
        with:
          repository: ${{github.actor}}/challenge-ci-cd
          ref: main
          token: ${{ secrets.MY_PAT }}
          persist-credentials: true
      - name: update resources
        working-directory: kubernetes/auth
        run: 'sed -i "s/\(image: lodenn\/auth-api:\)[a-f0-9]*/\1${{ github.sha }}/" deployment.yaml'
      - name: configure git
        run: |
          git config --global user.email "khalednasser788@gmail.com"
          git config --global user.name "Lodenn"
          git add -A
          git commit -am "update image ${{ github.sha }}"
          git push origin main
  cluster-update:
    needs: deploy
    runs-on: ubuntu-latest
    environment: development
    steps:
      - name: Get the code
        uses: actions/checkout@v4
        with:
          repository: ${{github.actor}}/challenge-ci-cd
          ref: main
          token: ${{ secrets.MY_PAT }}
          persist-credentials: true
      - name: Set up Kubectl
        uses: azure/setup-kubectl@v1
      - name: Deploy to Minikube
        working-directory: kubernetes/auth
        run: |
          kubectl config set-credentials lodenn --username=admin --password=123456
          kubectl config set-cluster minikube --server=https://3a4b-45-243-168-75.ngrok-free.app --insecure-skip-tls-verify=true
          kubectl config set-context minikube --cluster=minikube --user=lodenn
          kubectl config use-context minikube
          kubectl apply -f development.yaml
