name: Auth Workflow
on:
  push:
    branches:
      - auth
env:
  TOKEN_KEY: secrettoken
jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Get the code
        uses: actions/checkout@v3
      - name: Install main dependencies
        uses: ./.github/actions/setup
        with:
          working_dir: users-api
  build-auth-image:
    needs: setup
    uses: ./.github/workflows/image-builder.yml
    with:
      working_dir: auth-api
      image: auth-api
    secrets:
      docker_hub_user: ${{ secrets.DOCKER_HUB_USER }}
      docker_hub_pass: ${{ secrets.DOCKER_HUB_PASS }}
  deploy:
    needs: build-auth-image
    runs-on: ubuntu-latest
    environment: development
    permissions:
      contents: write
    steps:
      - name: Get the code
        uses: actions/checkout@v4
        with:
          repository: ${{github.actor}}/challenge-ci-cd
          ref: main
          token: ${{ secrets.GITHUB_TOKEN }}
          persist-credentials: true
      - name: update resources
        working-directory: kubernetes/auth
        run: sed -i 's/latest/${{ github.sha }}/g' deployment.yaml
      - name: configure git
        run: |
          git config --global user.email "khalednasser788@gmail.com"
          git config --global user.name "Lodenn"
          git remote add origin https://x-access-token:${{ secrets.MY_PAT }}@github.com/Lodennn/challenge-ci-cd.git
          git add .
          git commit -am "update image ${{ github.sha }}"
          git push origin main
