name: Auth Workflow
on:
  push:
    branches:
      - develop
jobs:
  setup:
    uses: ./.github/workflows/setup.yml
    with:
      working_dir: auth-api
  build:
    needs: setup
    uses: ./.github/workflows/image-builder.yml
    with:
      working_dir: auth-api
      image: auth-api
