name: Auth Workflow
on:
  push:
    branches:
      - auth
env:
  TOKEN_KEY: secrettoken
jobs:
  setup:
    uses: ./.github/workflows/setup.yml
    with:
      working_dir: auth-api
  build:
    needs: setup
    uses: ./.github/workflows/image-builder.yml
    with:
      working_dir: auth-api
      image: auth-api
    secrets:
      docker_hub_user: ${{ secrets.DOCKER_HUB_USER }}
      docker_hub_pass: ${{ secrets.DOCKER_HUB_PASS }}
