name: Auth Workflow
on:
  push:
    branches:
      - develop
jobs:
  setup:
    name: setting up project
    uses: ./.github/workflows/reusable/setup.yml
    with:
      working_dir: auth-api
    # runs-on: ubuntu-latest
    # steps:
    # - name: Get the code
    #   uses: actions/checkout@v3
    # - name: cache dependencies
    #   uses: actions/cache@v3
    #   id: cache
    #   with:
    #     key: dep-node-modules-${{ github.sha }}
    #     path: ~/.npm
    # - name: install dependencies
    #   if: ${{ steps.cache.outputs.cache-hit != 'true' }}
    #   working-directory: auth-api
    #   run: npm install
  build:
    environment: development
    needs: setup
    name: build auth image
    runs-on: ubuntu-latest
    steps:
      - name: Get the code
        uses: actions/checkout@v3
      - name: build auth api image
        working-directory: auth-api
        env:
          TOKEN_KEY: topsecrettoken
        run: docker build -t ${{ secrets.DOCKER_HUB_USER }}/auth-api .
      - name: login to docker hub
        run: docker login -u ${{ secrets.DOCKER_HUB_USER }} -p ${{ secrets.DOCKER_HUB_PASS }}
      - name: push docker image
        working-directory: auth-api
        run: docker push ${{ secrets.DOCKER_HUB_USER }}/auth-api:latest
