name: Image Builder
on:
  workflow_call:
    inputs:
      working_dir:
        required: true
        type: string
        description: this input helps to determine which folder should we setup
      image:
        required: true
        type: string
        description: image name to be built/pushed
    secrets:
      docker_hub_user:
        required: true
        description: docker repo username to upload the image
      docker_hub_pass:
        required: true
        description: docker repo password to upload the image
jobs:
  build:
    environment: development
    name: build ${{ inputs.image }} image
    runs-on: ubuntu-latest
    steps:
      - name: Get the code
        uses: actions/checkout@v3
      - name: check working_dir
        run: echo "${{ inputs.working_dir }} - ${{ inputs.image }}"
      - name: build ${{ inputs.image }} image
        working-directory: ${{ inputs.working_dir }}
        run: |
          echo "docker build -t ${{ secrets.docker_hub_user }}/${{ inputs.image }} ."
          docker build -t ${{ secrets.docker_hub_user }}/${{ inputs.image }} .
      - name: login to docker hub
        run: docker login -u ${{ secrets.docker_hub_user }} -p ${{ secrets.docker_hub_pass }}
      - name: push docker image
        working-directory: ${{ inputs.image }}
        run: docker push ${{ secrets.docker_hub_user }}/${{ inputs.image }}
