name: Image Builder
on:
  workflow_call:
    inputs:
      working_dir:
        required: true
        type: string
        description: this input helps to determine which folder should we setup
      image:
        required: true
        type: string
        description: image name to be built/pushed
jobs:
  build:
    environment: development
    name: build ${{ inputs.image }} image
    runs-on: ubuntu-latest
    steps:
      - name: Get the code
        uses: actions/checkout@v3
      - name: check working_dir
        run: echo "${{ inputs.working_dir }} - ${{ inputs.image }}"
      - name: build ${{ inputs.image }} image
        working-directory: ${{ inputs.working_dir }}
        env:
          TOKEN_KEY: topsecrettoken
        run: |
          echo "docker build -t ${{ secrets.DOCKER_HUB_USER }}/${{ inputs.image }} ."
          docker build -t ${{ secrets.DOCKER_HUB_USER }}/${{ inputs.image }} .
      - name: login to docker hub
        run: docker login -u ${{ secrets.DOCKER_HUB_USER }} -p ${{ secrets.DOCKER_HUB_PASS }}
      - name: push docker image
        working-directory: ${{ inputs.image }}
        run: docker push ${{ secrets.DOCKER_HUB_USER }}/${{ inputs.image }}:latest
