name: Setup mongodb
on:
  push:
    branches:
      - develop
jobs:
  setup:
    runs-on: ubuntu-latest
    env:
      MONGO_INITDB_DATABASE: users
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: secret
      MONGO_DB_HOST: mongodb
    steps:
      - name: Get the code
        uses: actions/checkout@v3
      - name: display environment vaiables
        run: |
          echo "MONGO_INITDB_DATABASE: $MONGO_INITDB_DATABASE
              MONGO_INITDB_ROOT_USERNAME: $MONGO_INITDB_ROOT_USERNAME
              MONGO_INITDB_ROOT_PASSWORD: $MONGO_INITDB_ROOT_PASSWORD
              MONGO_DB_HOST: $MONGO_DB_HOST"
      - name: Run mongodb container
        run: |
          docker run --name mongodb -v "D:\Programming\Courses\Docker, Kubernetes, CICD\challenge:/data/db" -e MONGO_INITDB_DATABASE=users -e MONGO_INITDB_ROOT_USERNAME=admin  -e MONGO_INITDB_ROOT_PASSWORD=secret  -e MONGO_DB_HOST=mongodb  mongo
