name: Setup mongodb
on:
  push:
    branches:
      - develop
env:
  MONGO_INITDB_DATABASE: users
  MONGO_INITDB_ROOT_USERNAME: admin
  MONGO_INITDB_ROOT_PASSWORD: secret
  MONGO_DB_HOST: mongodb
jobs:
  setup:
    name: "setup the code"
    runs-on: ubuntu-latest
    steps:
      - name: Get the code
        uses: actions/checkout@v3
      - name: display environment vaiables
        run: |
          echo "MONGO_INITDB_DATABASE: $MONGO_INITDB_DATABASE
              MONGO_INITDB_ROOT_USERNAME: $MONGO_INITDB_ROOT_USERNAME
              MONGO_INITDB_ROOT_PASSWORD: $MONGO_INITDB_ROOT_PASSWORD
              MONGO_DB_HOST: $MONGO_DB_HOST"
      - name: Run mongodb container
        id: runner
        run: |
          docker run --name mongodb \
          -e MONGO_INITDB_DATABASE=$MONGO_INITDB_DATABASE \
          -e MONGO_INITDB_ROOT_USERNAME=$MONGO_INITDB_ROOT_USERNAME \
          -e MONGO_INITDB_ROOT_PASSWORD=$MONGO_INITDB_ROOT_PASSWORD \
          -e MONGO_DB_HOST=$MONGO_DB_HOST \
          --rm \
          -d \
          mongo
      - name: Check for mongodb status
        if: success() && ${{ steps.runner.outcome.success }}
        run: echo "mongodb container is running..."
