name: Users Workflow
on:
  push:
    branches:
      - users
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Get the code
        uses: actions/checkout@v3
      - name: Install main dependencies
        uses: ./.github/actions/setup
        with:
          working_dir: users-api
      - name: Install extra dependencies for testing
        working-directory: users-api
        run: npm install --save-dev jest @shelf/jest-mongodb
      - name: Run test
        id: test
        working-directory: users-api
        run: |
          ls
          npm run test
      - name: Upload test report
        if: failure() && steps.test.outcome == 'failure'
        uses: actions/upload-artifact@v3
        with:
          name: test-reports
          path: ./users-api/reports/

  build:
    needs: test
    uses: ./.github/workflows/image-builder.yml
    with:
      working_dir: users-api
      image: users-api
    secrets:
      docker_hub_user: ${{ secrets.DOCKER_HUB_USER }}
      docker_hub_pass: ${{ secrets.DOCKER_HUB_PASS }}
