name: Users Workflow
on:
  push:
    branches:
      - users
jobs:
  setup:
    uses: ./.github/workflows/setup.yml
    with:
      working_dir: users-api
  build:
    needs: setup
    uses: ./.github/workflows/image-builder.yml
    with:
      working_dir: users-api
      image: users-api
    secrets:
      docker_hub_user: ${{ secrets.DOCKER_HUB_USER }}
      docker_hub_pass: ${{ secrets.DOCKER_HUB_PASS }}
  test-database:
    needs: build
    runs-on: ubuntu-latest
    # container:
    #   image: lodenn/users-api:latest
    env:
      MONGO_INITDB_DATABASE: users
      MONGO_INITDB_ROOT_USERNAME: admin # 👈 should be github secrets
      MONGO_INITDB_ROOT_PASSWORD: secret # 👈 should be github secrets
      MONGO_DB_HOST: mongodb
      AUTH_API_ADDRESS: auth:3000
      LISTEN: false
    services:
      mongodb:
        image: mongo
        ports:
          - 27017:27017
        env:
          MONGO_INITDB_DATABASE: users
          MONGO_INITDB_ROOT_USERNAME: admin # 👈 should be github secrets
          MONGO_INITDB_ROOT_PASSWORD: secret # 👈 should be github secrets
      auth:
        image: lodenn/auth-api:latest
        env:
          TOKEN_KEY: secrettoken
          LISTEN: false
        ports:
          - 3000:3000
      users:
        image: lodenn/users-api:latest
        ports:
          - 80:80
        env:
          LISTEN: false
    steps:
      - name: Get the code
        uses: actions/checkout@v3
      - name: cache dependencies
        uses: actions/cache@v3
        id: cache
        with:
          key: dep-node-modules-${{ github.sha }}
          path: users-api/~/.npm
      - name: install dependencies
        if: ${{ steps.cache.outputs.cache-hit != 'true' }}
        working-directory: users-api
        run: npm install
      - name: run users container
        working-directory: users-api
        run: node users-app.js
