name: Users Workflow
on:
  push:
    branches:
      - users
jobs:
  setup:
    uses: ./.github/workflows/setup.yml
    with:
      working_dir: users-api
  test:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - name: Display information
        run: ${{ github.workspace }}
      - name: Getting the code
        uses: ./.github/workflows/setup.yml
        with:
          working_dir: users-api
      - name: Install extra dependencies for testing
        working-directory: users-api
        run: npm install --save-dev @shelf/jest-mongodb
      - name: Run test
        run: npm run test
  build:
    needs: test
    uses: ./.github/workflows/image-builder.yml
    with:
      working_dir: users-api
      image: users-api
    secrets:
      docker_hub_user: ${{ secrets.DOCKER_HUB_USER }}
      docker_hub_pass: ${{ secrets.DOCKER_HUB_PASS }}
