name: Users Workflow
on:
  push:
    branches:
      - users
jobs:
  test:
    environment: development
    runs-on: ubuntu-latest
    env:
      MONGO_INITDB_DATABASE: users
      MONGO_INITDB_ROOT_USERNAME: ${{ secrets.MONGO_INITDB_ROOT_USERNAME }}
      MONGO_INITDB_ROOT_PASSWORD: ${{ secrets.MONGO_INITDB_ROOT_PASSWORD }}
      MONGO_DB_HOST: 127.0.0.1:27017
      AUTH_API_ADDRESS: auth:3000
    services:
      mongodb:
        image: mongo
        ports:
          - 27017:27017
        env:
          MONGO_INITDB_DATABASE: users
          MONGO_INITDB_ROOT_USERNAME: ${{ env.MONGO_INITDB_ROOT_USERNAME }}
          MONGO_INITDB_ROOT_PASSWORD: ${{ env.MONGO_INITDB_ROOT_PASSWORD }}

    steps:
      - name: Get the code
        uses: actions/checkout@v3
      - name: Install main dependencies
        uses: ./.github/actions/setup
        with:
          working_dir: users-api
      - name: adding caching layer on extra dependencies
        uses: actions/cache@v3
        id: test-deps-cache
        with:
          key: testing-dep-${{ github.sha }}
          path: users-api/~/.npm
      - name: Install extra dependencies for testing
        if: steps.test-deps-cache.outcome.cache-hit != 'true'
        working-directory: users-api
        run: npm install --save-dev jest jest-junit @shelf/jest-mongodb
      - name: Run test
        id: test
        working-directory: users-api
        run: npm run test
      - name: Upload test report
        if: failure() && steps.test.outcome == 'failure'
        uses: actions/upload-artifact@v3
        with:
          name: database-connection-test-report
          path: ./users-api/reports/
  build-users-image:
    needs: test
    uses: ./.github/workflows/image-builder.yml
    with:
      working_dir: users-api
      image: users-api
      image-tag: ${{ github.sha }}
    secrets:
      docker_hub_user: ${{ secrets.DOCKER_HUB_USER }}
      docker_hub_pass: ${{ secrets.DOCKER_HUB_PASS }}
  deploy:
    needs: build-users-image
    runs-on: ubuntu-latest
    environment: development
    permissions:
      contents: write
    steps:
      - name: Get the code
        uses: actions/checkout@v4
        with:
          repository: ${{github.actor}}/challenge-ci-cd
          ref: main
          token: ${{ secrets.MY_PAT }}
          persist-credentials: true
      - name: update resources
        working-directory: kubernetes/users
        run: 'sed -i "s/\(image: lodenn\/users-api:\)[a-f0-9]*/\1${{ github.sha }}/" deployment.yaml'
      - name: configure git
        run: |
          git config --global user.email "khalednasser788@gmail.com"
          git config --global user.name "Lodenn"
          git add -A
          git commit -am "update image ${{ github.sha }}"
          git push origin main
