name: Users Workflow
on:
  push:
    branches:
      - users
jobs:
  test:
    runs-on: ubuntu-latest
    env:
      MONGO_INITDB_DATABASE: users
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: secret
      MONGO_DB_HOST: 127.0.0.1:27017
      # AUTH_API_ADDRESS: auth:3000
    services:
      mongodb:
        image: mongo
        ports:
          - 27017:27017
        env:
          MONGO_INITDB_DATABASE: users
          MONGO_INITDB_ROOT_USERNAME: admin # 👈 should be github secrets
          MONGO_INITDB_ROOT_PASSWORD: secret # 👈 should be github secrets

    steps:
      - name: Get the code
        uses: actions/checkout@v3
      - name: Install main dependencies
        uses: ./.github/actions/setup
        with:
          working_dir: users-api
      - name: Install extra dependencies for testing
        working-directory: users-api
        run: npm install --save-dev jest jest-junit @shelf/jest-mongodb
      - name: Run test
        id: test
        working-directory: users-api
        run: npm run test
      - name: Upload test report
        if: failure() && steps.test.outcome == 'failure'
        uses: actions/upload-artifact@v3
        with:
          name: test-reports
          path: ./users-api/reports/

  build:
    needs: test
    uses: ./.github/workflows/image-builder.yml
    with:
      working_dir: users-api
      image: users-api
    secrets:
      docker_hub_user: ${{ secrets.DOCKER_HUB_USER }}
      docker_hub_pass: ${{ secrets.DOCKER_HUB_PASS }}
