name: Users Workflow
on:
  push:
    branches:
      - users
jobs:
  # setup:
  #   uses: ./.github/workflows/setup.yml
  #   with:
  #     working_dir: users-api
  test:
    runs-on: ubuntu-latest
    steps:
      # - name: Getting the code
      #   uses: ./.github/workflows/setup.yml
      #   with:
      #     working_dir: users-api
      - name: Get the code
        uses: actions/checkout@v3
      - name: Install main dependencies
        uses: ./.github/actions/setup
        with:
          working_dir: users-api
      - name: Install extra dependencies for testing
        working-directory: users-api
        run: npm install --save-dev @shelf/jest-mongodb
      - name: Run test
        working-directory: users-api
        run: npm run test
  build:
    needs: test
    uses: ./.github/workflows/image-builder.yml
    with:
      working_dir: users-api
      image: users-api
    secrets:
      docker_hub_user: ${{ secrets.DOCKER_HUB_USER }}
      docker_hub_pass: ${{ secrets.DOCKER_HUB_PASS }}
